Execute: RooSimplepTPbPb_split.cxx
	g++ RooSimplepTPbPb_split.cxx -o Execute \
		-I/afs/cern.ch/user/h/hbossi/RooUnfold/src -L/afs/cern.ch/user/h/hbossi/RooUnfold/ -lRooUnfold \
		`root-config --cflags --glibs`
